export {
  autoSolverBackend,
  buildOpenFeaCoreModelForStudy,
  coreMeshStatisticsForStudy,
  geometrySourceForStudy,
  explicitSolverBackend,
  hasActualCoreVolumeMesh,
  hasMeshableGeometrySource,
  isComplexGeometry,
  isSimpleBlockLikeDisplayModel,
  normalizeSolverBackend,
  OPENFEA_CORE_MESH_REQUIRED_REASON,
  openFeaCoreEligibility,
  resolveSolverBackend,
  studyForCoreGeometryDispatch,
  trySolveOpenFeaCoreStudy,
  trySolveOpenFeaCoreStudyAutomatic,
  type CoreCloudGeometrySource,
  type CoreMeshStatistics,
  type CoreSolveCapabilities,
  type NormalizedBrowserSolverBackend,
  type OpenFeaCoreEligibility,
  type OpenFeaCoreSolveOutcome,
  type ResolvedSolverBackend
} from "@openfea/core-adapter";
