import type { DisplayModel, Project, ResultField, ResultSummary, Study } from "@opencae/schema";
import type { SolverSurfaceMesh } from "./projectFile";

export type ResultViewerPayload = {
  format: "opencae-result-viewer";
  version: 1;
  exportedAt: string;
  project: { name: string; unitSystem: Project["unitSystem"] };
  study: { name: string; type: Study["type"] };
  displayModel: Pick<DisplayModel, "name" | "bodyCount" | "dimensions">;
  summary: ResultSummary;
  fields: ResultField[];
  surfaceMesh: SolverSurfaceMesh;
};

export function buildResultViewerHtml(input: {
  project: Project;
  study: Study;
  displayModel: DisplayModel;
  summary: ResultSummary;
  fields: ResultField[];
  surfaceMesh: SolverSurfaceMesh;
  exportedAt?: string;
}): string {
  const payload: ResultViewerPayload = {
    format: "opencae-result-viewer",
    version: 1,
    exportedAt: input.exportedAt ?? new Date().toISOString(),
    project: { name: input.project.name, unitSystem: input.project.unitSystem },
    study: { name: input.study.name, type: input.study.type },
    displayModel: { name: input.displayModel.name, bodyCount: input.displayModel.bodyCount, dimensions: input.displayModel.dimensions },
    summary: input.summary,
    fields: input.fields,
    surfaceMesh: input.surfaceMesh
  };
  const encodedPayload = encodeBase64Utf8(JSON.stringify(payload));
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'">
<title>OpenCAE result viewer</title><style>${RESULT_VIEWER_CSS}</style></head>
<body><header><span class="mark">O</span><span><strong id="projectName">OpenCAE result</strong><small id="studyName"></small></span><span class="offline">Self-contained · offline</span></header>
<main><section class="viewport"><canvas id="canvas" aria-label="Interactive finite element result"></canvas><div id="error" class="error" hidden></div><div class="hint">Drag to rotate · Scroll to zoom</div></section>
<aside><label>Result field<select id="field"></select></label><label id="frameLabel">Frame<input id="frame" type="range" min="0" max="0" value="0"><span id="frameValue"></span></label>
<label>Deformation scale<input id="deformation" type="range" min="0" max="20" step="0.1" value="1"><span id="deformationValue">1.0×</span></label>
<button id="fit" type="button">Fit view</button><div class="legend"><div class="legend-bar"></div><span id="legendMin">0</span><span id="legendMax">1</span></div>
<div id="metrics" class="metrics"></div><details><summary>Provenance</summary><pre id="provenance"></pre></details></aside></main>
<footer>Generated by OpenCAE · <span id="exportedAt"></span></footer>
<script id="opencae-result-data" type="application/octet-stream">${encodedPayload}</script><script>${RESULT_VIEWER_SCRIPT}</script></body></html>`;
}

export function suggestedResultHtmlFilename(projectName: string): string {
  const slug = projectName.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return `${slug || "opencae"}-results.html`;
}

export function resultViewerPayloadFromHtml(html: string): ResultViewerPayload | null {
  const match = html.match(/<script id="opencae-result-data" type="application\/octet-stream">([A-Za-z0-9+/=]+)<\/script>/);
  if (!match?.[1]) return null;
  return JSON.parse(decodeBase64Utf8(match[1])) as ResultViewerPayload;
}

function encodeBase64Utf8(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (let offset = 0; offset < bytes.length; offset += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000));
  }
  return btoa(binary);
}

function decodeBase64Utf8(value: string): string {
  const binary = atob(value);
  const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

const RESULT_VIEWER_CSS = `
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#080c11;color:#e7edf5}*{box-sizing:border-box}body{margin:0;height:100vh;display:grid;grid-template-rows:56px minmax(0,1fr) 28px;background:#080c11}header,footer{display:flex;align-items:center;gap:12px;padding:0 18px;border-bottom:1px solid #263140;background:#111821}header>span:nth-child(2){display:grid}.mark{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#4da3ff;color:#04121f;font-weight:900}small,.offline,footer{color:#8b949e}.offline{margin-left:auto;font-size:12px}main{display:grid;grid-template-columns:minmax(0,1fr) 310px;min-height:0}.viewport{position:relative;min-height:0;background:radial-gradient(circle at 50% 45%,#15202d,#070b10 68%)}canvas{display:block;width:100%;height:100%}.hint{position:absolute;left:14px;bottom:12px;padding:6px 9px;border-radius:6px;background:#111821cc;color:#8b949e;font-size:11px}.error{position:absolute;inset:20px;display:grid;place-items:center;color:#ef4444}aside{overflow:auto;padding:18px;border-left:1px solid #263140;background:#111821}label{display:grid;gap:7px;margin-bottom:17px;color:#aeb9c7;font-size:12px}select,input,button{width:100%;font:inherit}select,button{padding:9px 10px;border:1px solid #354154;border-radius:7px;color:#e7edf5;background:#17202b}button{cursor:pointer}.legend{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:18px 0}.legend-bar{grid-column:1/-1;height:10px;border-radius:999px;background:linear-gradient(90deg,#0759d6,#0ea5e9,#22c55e,#facc15,#f97316,#ef4444)}.legend span:last-child{text-align:right}.metrics{display:grid;gap:8px}.metric{padding:10px;border:1px solid #263140;border-radius:8px;background:#17202b}.metric small,.metric strong{display:block}.metric strong{margin-top:3px}details{margin-top:18px;color:#aeb9c7}pre{white-space:pre-wrap;font-size:10px;color:#8b949e}footer{justify-content:center;border-top:1px solid #263140;border-bottom:0;font-size:10px}@media(max-width:760px){main{grid-template-columns:1fr;grid-template-rows:minmax(320px,1fr) auto}aside{border-left:0;border-top:1px solid #263140}}`;

const RESULT_VIEWER_SCRIPT = String.raw`
const VERT='#version 300 es\nprecision highp float;in vec3 aPosition;in vec3 aColor;in vec3 aDisplacement;uniform mat4 uMatrix;uniform vec3 uCenter;uniform float uScale;uniform float uDeform;out vec3 vColor;void main(){gl_Position=uMatrix*vec4((aPosition-uCenter+aDisplacement*uDeform)*uScale,1.0);vColor=aColor;}';
const FRAG='#version 300 es\nprecision highp float;in vec3 vColor;out vec4 outColor;void main(){outColor=vec4(vColor,1.0);}';
(()=>{'use strict';const dataNode=document.getElementById('opencae-result-data');const decode=s=>new TextDecoder().decode(Uint8Array.from(atob(s),c=>c.charCodeAt(0)));let data;try{data=JSON.parse(decode(dataNode.textContent.trim()))}catch(e){showError('The embedded OpenCAE result is invalid.');return}document.getElementById('projectName').textContent=data.project.name;document.getElementById('studyName').textContent=data.study.name;document.getElementById('exportedAt').textContent=new Date(data.exportedAt).toLocaleString();document.getElementById('provenance').textContent=JSON.stringify(data.summary.provenance||{},null,2);const metrics=document.getElementById('metrics');const s=data.summary;if(typeof s.maxStress==='number')metrics.innerHTML=metric('Peak stress',s.maxStress,s.maxStressUnits)+metric('Peak displacement',s.maxDisplacement,s.maxDisplacementUnits)+metric('Safety factor',s.safetyFactor,'')+metric('Reaction',s.reactionForce,s.reactionForceUnits);else if(Array.isArray(s.modes))metrics.innerHTML=metric('Converged modes',s.convergedModeCount,'')+metric('First frequency',s.modes[0]?.frequencyHz||0,'Hz');else if(s.analysisType==='steady_state_thermal')metrics.innerHTML=metric('Minimum temperature',s.minTemperature,s.temperatureUnits)+metric('Maximum temperature',s.maxTemperature,s.temperatureUnits)+metric('Peak heat flux',s.maxHeatFlux,s.heatFluxUnits)+metric('Energy balance error',100*(s.energyBalanceRelativeError||0),'%');
const mesh=data.surfaceMesh,nodes=mesh.nodes||[],triangles=mesh.triangles||[];if(!nodes.length||!triangles.length){showError('This result does not include a solver surface mesh.');return}const fields=(data.fields||[]).filter(f=>Array.isArray(f.values)&&f.values.length===nodes.length);if(!fields.length){showError('No result field aligns with the solver surface mesh.');return}const groups=new Map;for(const f of fields){const key=f.type+':'+(f.component||'');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(f)}for(const list of groups.values())list.sort((a,b)=>(a.frameIndex||a.modeIndex||0)-(b.frameIndex||b.modeIndex||0));const select=document.getElementById('field');for(const [key,list]of groups){const o=document.createElement('option');o.value=key;o.textContent=label(list[0]);select.appendChild(o)}const frame=document.getElementById('frame'),deformation=document.getElementById('deformation');let rx=-.45,ry=.65,zoom=2.8,drag=false,lastX=0,lastY=0;const canvas=document.getElementById('canvas'),gl=canvas.getContext('webgl2',{antialias:true});if(!gl){showError('WebGL 2 is required to view this result.');return}const program=createProgram(gl,VERT,FRAG);gl.useProgram(program);const positions=new Float32Array(nodes.flat()),indices=new Uint32Array(triangles.flat()),colors=new Float32Array(nodes.length*3),displacements=new Float32Array(nodes.length*3);const bounds=extent(nodes),center=bounds.center,scale=2/Math.max(bounds.size[0],bounds.size[1],bounds.size[2],1e-12);const posBuffer=buffer(gl,gl.ARRAY_BUFFER,positions),colorBuffer=buffer(gl,gl.ARRAY_BUFFER,colors),dispBuffer=buffer(gl,gl.ARRAY_BUFFER,displacements),indexBuffer=buffer(gl,gl.ELEMENT_ARRAY_BUFFER,indices);attribute(gl,program,'aPosition',posBuffer,3);attribute(gl,program,'aColor',colorBuffer,3);attribute(gl,program,'aDisplacement',dispBuffer,3);const uMatrix=gl.getUniformLocation(program,'uMatrix'),uCenter=gl.getUniformLocation(program,'uCenter'),uScale=gl.getUniformLocation(program,'uScale'),uDeform=gl.getUniformLocation(program,'uDeform');gl.uniform3fv(uCenter,center);gl.uniform1f(uScale,scale);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.clearColor(.027,.043,.063,1);
function update(){const list=groups.get(select.value)||fields;frame.max=String(Math.max(0,list.length-1));frame.disabled=list.length<2;document.getElementById('frameLabel').style.display=list.length<2?'none':'grid';const f=list[Math.min(Number(frame.value),list.length-1)]||list[0];document.getElementById('frameValue').textContent=f.timeSeconds!==undefined?f.timeSeconds.toFixed(5)+' s':f.modeIndex?'Mode '+f.modeIndex:'';document.getElementById('legendMin').textContent=fmt(f.min)+' '+f.units;document.getElementById('legendMax').textContent=fmt(f.max)+' '+f.units;for(let i=0;i<f.values.length;i++){const c=ramp((f.values[i]-f.min)/Math.max(f.max-f.min,Number.EPSILON));colors.set(c,i*3)}const df=fields.find(x=>(x.type==='displacement'||x.type==='mode_shape')&&x.frameIndex===f.frameIndex&&x.modeIndex===f.modeIndex&&Array.isArray(x.vectors));displacements.fill(0);if(df)for(let i=0;i<Math.min(nodes.length,df.vectors.length);i++)displacements.set(df.vectors[i],i*3);gl.bindBuffer(gl.ARRAY_BUFFER,colorBuffer);gl.bufferData(gl.ARRAY_BUFFER,colors,gl.DYNAMIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,dispBuffer);gl.bufferData(gl.ARRAY_BUFFER,displacements,gl.DYNAMIC_DRAW);draw()}
function draw(){resize();gl.viewport(0,0,canvas.width,canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniformMatrix4fv(uMatrix,false,matrix(canvas.width/canvas.height,rx,ry,zoom));gl.uniform1f(uDeform,Number(deformation.value));gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,indexBuffer);gl.drawElements(gl.TRIANGLES,indices.length,gl.UNSIGNED_INT,0)}select.onchange=()=>{frame.value='0';update()};frame.oninput=update;deformation.oninput=()=>{document.getElementById('deformationValue').textContent=Number(deformation.value).toFixed(1)+'×';draw()};document.getElementById('fit').onclick=()=>{rx=-.45;ry=.65;zoom=2.8;draw()};canvas.onpointerdown=e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;ry+=(e.clientX-lastX)*.008;rx+=(e.clientY-lastY)*.008;lastX=e.clientX;lastY=e.clientY;draw()};canvas.onpointerup=()=>drag=false;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(1.2,Math.min(8,zoom*Math.exp(e.deltaY*.001)));draw()};window.onresize=draw;update();
function showError(message){const e=document.getElementById('error');e.hidden=false;e.textContent=message}function metric(l,v,u){return '<div class="metric"><small>'+l+'</small><strong>'+fmt(v)+' '+u+'</strong></div>'}function label(f){return f.type.replaceAll('_',' ')+(f.component?' · '+f.component.replaceAll('_',' '):'')}function fmt(v){return Math.abs(v)>=1000?Math.round(v).toLocaleString():Number(v).toPrecision(4)}function extent(n){let lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const p of n)for(let i=0;i<3;i++){lo[i]=Math.min(lo[i],p[i]);hi[i]=Math.max(hi[i],p[i])}return{center:lo.map((v,i)=>(v+hi[i])/2),size:lo.map((v,i)=>hi[i]-v)}}function ramp(t){t=Math.max(0,Math.min(1,t));const stops=[[.029,.349,.839],[.055,.647,.914],[.133,.773,.369],[.98,.8,.082],[.976,.451,.086],[.937,.267,.267]],x=t*(stops.length-1),i=Math.min(stops.length-2,Math.floor(x)),a=x-i;return stops[i].map((v,j)=>v+(stops[i+1][j]-v)*a)}function resize(){const d=devicePixelRatio||1,w=Math.floor(canvas.clientWidth*d),h=Math.floor(canvas.clientHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}function buffer(g,target,data){const b=g.createBuffer();g.bindBuffer(target,b);g.bufferData(target,data,g.STATIC_DRAW);return b}function attribute(g,p,n,b,size){const l=g.getAttribLocation(p,n);g.bindBuffer(g.ARRAY_BUFFER,b);g.enableVertexAttribArray(l);g.vertexAttribPointer(l,size,g.FLOAT,false,0,0)}function createProgram(g,v,f){const p=g.createProgram(),vs=shader(g,g.VERTEX_SHADER,v),fs=shader(g,g.FRAGMENT_SHADER,f);g.attachShader(p,vs);g.attachShader(p,fs);g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw Error(g.getProgramInfoLog(p));return p}function shader(g,t,s){const x=g.createShader(t);g.shaderSource(x,s);g.compileShader(x);if(!g.getShaderParameter(x,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(x));return x}function matrix(aspect,x,y,z){const c=Math.cos,s=Math.sin,px=Math.PI/3,f=1/Math.tan(px/2),near=.1,far=20;const proj=new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]),mx=new Float32Array([1,0,0,0,0,c(x),s(x),0,0,-s(x),c(x),0,0,0,-z,1]),my=new Float32Array([c(y),0,-s(y),0,0,1,0,0,s(y),0,c(y),0,0,0,0,1]);return mul(proj,mul(mx,my))}function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}
})();`;
