// Spike test 2 (plan A-M1) — THE DAY-ONE BET VALIDATOR.
//
// Decides the viability of the whole in-browser meshing workstream: can
// gmsh-wasm import a real STEP file through its OpenCASCADE kernel and produce
// a valid 3D tet mesh? The fixture (fixtures/box-with-bore.step) was itself
// generated by gmsh-wasm's OCC kernel (box minus through-bore cylinder), so it
// exercises curved trimmed surfaces, not just planar boxes.
//
// If the default Delaunay 3D algorithm fails (documented WASM boundary-recovery
// issue), meshStepToMshV2 retries with Mesh.Algorithm3D = 4 (Frontal) and
// reports which algorithm succeeded.
import { readFileSync } from "node:fs";
import { connectedComponents } from "@opencae/core";
import { describe, expect, it } from "vitest";
import { parseGmshMeshToCoreVolumeMesh } from "./gmshMeshParser";
import { meshStepToMshV2 } from "./wasmMesher";
import type { CoreVolumeMeshArtifact } from "./types";

const FIXTURE_DIMENSIONS_MM = { x: 60, y: 40, z: 20, boreDiameter: 12 };

describe("gmsh-wasm STEP import + 3D mesh spike (day-one bet)", () => {
  it("imports box-with-bore.step via OCC and produces a valid Tet10 mesh", { timeout: 180_000 }, async () => {
    const step = readFileSync(new URL("../fixtures/box-with-bore.step", import.meta.url), "utf8");

    const started = Date.now();
    const meshed = await meshStepToMshV2(step, { elementOrder: 2, meshSizeMm: 6 });
    const wallMs = Date.now() - started;

    const artifact = parseGmshMeshToCoreVolumeMesh(meshed.msh, {
      units: "mm",
      diagnostics: ["gmsh-wasm spike STEP import"]
    });

    // Loud spike evidence — this is the deliverable.
    console.log(
      `[SPIKE step-import] VERDICT=${meshed.algorithm3D === "delaunay" ? "OK-default-delaunay" : "OK-frontal-fallback"} ` +
        `algorithm3D=${meshed.algorithm3D} nodes=${artifact.metadata.nodeCount} elements=${artifact.metadata.elementCount} ` +
        `tet10=${artifact.elements.filter((e) => e.type === "Tet10").length} ` +
        `surfaceFacets=${artifact.metadata.surfaceFacetCount} components=${artifact.metadata.connectedComponentCount} ` +
        `inverted=${artifact.metadata.meshQuality.invertedElementCount} wallMs=${wallMs} ` +
        `phases=${JSON.stringify(meshed.timings)}`
    );

    // A valid tet mesh resulted.
    expect(artifact.elements.length).toBeGreaterThan(0);
    expect(artifact.elements.every((element) => element.type === "Tet10")).toBe(true);
    expect(artifact.metadata.meshQuality.invertedElementCount).toBe(0);
    expect(artifact.metadata.meshQuality.minTetVolume).toBeGreaterThan(0);
    expect(artifact.metadata.connectedComponentCount).toBe(1);
    expect(coreConnectedComponentCount(artifact)).toBe(1);

    // Sane counts for a 60x40x20 mm block at ~6 mm characteristic length.
    expect(artifact.metadata.nodeCount).toBeGreaterThan(200);
    expect(artifact.metadata.nodeCount).toBeLessThan(500_000);
    expect(artifact.metadata.elementCount).toBeGreaterThan(100);
    expect(artifact.metadata.elementCount).toBeLessThan(250_000);

    // Volume sanity: box minus through-bore, mm^3 -> m^3. Linear corner-tet
    // volumes under-resolve the bore slightly, so allow 5%.
    const { x, y, z, boreDiameter } = FIXTURE_DIMENSIONS_MM;
    const expectedVolumeM3 = (x * y * z - Math.PI * (boreDiameter / 2) ** 2 * z) * 1e-9;
    const volume = meshVolumeM3(artifact);
    expect(volume).toBeGreaterThan(expectedVolumeM3 * 0.95);
    expect(volume).toBeLessThan(expectedVolumeM3 * 1.05);

    // Bounding box sanity (parser scales mm -> m).
    const bounds = boundingBox(artifact.nodes.coordinates);
    expect(bounds.max[0] - bounds.min[0]).toBeCloseTo(x * 1e-3, 4);
    expect(bounds.max[1] - bounds.min[1]).toBeCloseTo(y * 1e-3, 4);
    expect(bounds.max[2] - bounds.min[2]).toBeCloseTo(z * 1e-3, 4);
  });
});

function coreConnectedComponentCount(artifact: CoreVolumeMeshArtifact): number {
  return connectedComponents({
    nodes: { coordinates: artifact.nodes.coordinates },
    elementBlocks: [
      {
        name: "solid",
        type: "Tet10",
        material: "solid",
        connectivity: artifact.elements.flatMap((element) => element.connectivity)
      }
    ]
  }).componentCount;
}

function meshVolumeM3(artifact: CoreVolumeMeshArtifact): number {
  const coordinates = artifact.nodes.coordinates;
  let volume = 0;
  for (const element of artifact.elements) {
    const [a, b, c, d] = element.connectivity;
    volume += signedTetVolume(coordinates, a!, b!, c!, d!);
  }
  return volume;
}

function signedTetVolume(coordinates: number[], a: number, b: number, c: number, d: number): number {
  const ax = coordinates[a * 3]!, ay = coordinates[a * 3 + 1]!, az = coordinates[a * 3 + 2]!;
  const bx = coordinates[b * 3]! - ax, by = coordinates[b * 3 + 1]! - ay, bz = coordinates[b * 3 + 2]! - az;
  const cx = coordinates[c * 3]! - ax, cy = coordinates[c * 3 + 1]! - ay, cz = coordinates[c * 3 + 2]! - az;
  const dx = coordinates[d * 3]! - ax, dy = coordinates[d * 3 + 1]! - ay, dz = coordinates[d * 3 + 2]! - az;
  return (bx * (cy * dz - cz * dy) - by * (cx * dz - cz * dx) + bz * (cx * dy - cy * dx)) / 6;
}

function boundingBox(coordinates: number[]): { min: [number, number, number]; max: [number, number, number] } {
  const min: [number, number, number] = [Infinity, Infinity, Infinity];
  const max: [number, number, number] = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < coordinates.length; i += 3) {
    for (let axis = 0; axis < 3; axis += 1) {
      const value = coordinates[i + axis]!;
      if (value < min[axis]!) min[axis] = value;
      if (value > max[axis]!) max[axis] = value;
    }
  }
  return { min, max };
}
