export {
  autoSolverBackend,
  buildOpenCaeCoreCloudModelForStudy,
  cloudGeometrySourceForStudy,
  explicitSolverBackend,
  hasActualCoreVolumeMesh,
  hasCloudMeshableGeometry,
  isComplexGeometry,
  isSimpleBlockLikeDisplayModel,
  normalizeSolverBackend,
  OPENCAE_CORE_CLOUD_GEOMETRY_REQUIRED_REASON,
  openCaeCoreEligibility,
  resolveSolverBackend,
  studyForCoreCloudGeometryDispatch,
  trySolveOpenCaeCoreStudy,
  type CoreCloudGeometrySource,
  type NormalizedBrowserSolverBackend,
  type OpenCaeCoreEligibility,
  type OpenCaeCoreSolveOutcome,
  type ResolvedSolverBackend
} from "@opencae/core-adapter";
