export {
  autoSolverBackend,
  buildOpenCaeCoreModelForStudy,
  coreMeshStatisticsForStudy,
  geometrySourceForStudy,
  explicitSolverBackend,
  hasActualCoreVolumeMesh,
  hasMeshableGeometrySource,
  isComplexGeometry,
  isSimpleBlockLikeDisplayModel,
  normalizeSolverBackend,
  OPENCAE_CORE_MESH_REQUIRED_REASON,
  openCaeCoreEligibility,
  resolveSolverBackend,
  studyForCoreGeometryDispatch,
  trySolveOpenCaeCoreStudy,
  type CoreCloudGeometrySource,
  type CoreMeshStatistics,
  type CoreSolveCapabilities,
  type NormalizedBrowserSolverBackend,
  type OpenCaeCoreEligibility,
  type OpenCaeCoreSolveOutcome,
  type ResolvedSolverBackend
} from "@opencae/core-adapter";
